### ISSUE TITLE
Set opacity for layers individually

### ISSUE THREAD

**Issue by abrobia** [dayjournal/Leaflet.Control.Opacity#1]
Hello, so happy to find this amazing plugin! Could be possible to set the layers opacity individually? I mean, for example, set the opacity only for the _"GSI Pale": t_pale_ layer and  _"GSI Ort": t_ort_, instead to set the opacity for all layers group?
Thanks a lot in advance.

**Comment by dayjournal** [comment]
With this plug-in, it is possible to set opacity for each layer.

<br>

Set it like when using LayerControl.

```
//AddLayer
var Map_AddLayer = {
    "OSM": o_std,
    "GSI Pale": t_pale,
    "GSI Ort": t_ort
};

```

<br>

After that, I will set the loading of the plugin.

```
//OpacityControl
L.control.opacity(
    Map_AddLayer
).addTo(map);

```

<br>

For details, please check the examples.

[example](https://github.com/dayjournal/Leaflet.Control.Opacity/tree/master/docs)

**Comment by abrobia** [comment]
Thanks for replying. Anyway, I was just interested in setting the opacity for some of the layers into the "var Map-AddLayer".  In my project, I have a great number of overlayers but I do not need to apply the opacity control for all of them; only for a few of them. Thanks in any case.

**Comment by dayjournal** [comment]
Apart from the background layer, you can also set only layers that you want to have opacity.

```
//AddLayer
var Map_AddLayer = {
    "OSM": o_std,
    "GSI Pale": t_pale,
    "GSI Ort": t_ort
};

//LayerControl
L.control.layers(
    Map_BaseLayer, 
    Map_AddLayer, 
    {
    collapsed: false
    }
).addTo(map);
```

```
//OpacityLayer
var Map_AddLayer = {
    "GSI Ort": t_ort
};

//OpacityControl
L.control.opacity(
    Map_AddLayer
).addTo(map);
```

**Comment by abrobia** [comment]
That's exactly what I needed. Thank you so much for taking time adding an example
