### ISSUE TITLE
drag and drop

### ISSUE THREAD

**Issue by webmap2015** [dayjournal/Leaflet.Control.Opacity#10]
Hi, I want to talk about two things

First, 
If I drag and drop opacity control, it's working. But, I want to only drag the range slider to adjust.

Like, http://lizardtechblog.github.io/Leaflet.OpacityControls/

with percentage rate

Like, https://docs.mapbox.com/mapbox-gl-js/example/adjust-layer-opacity/

Second, 
Is it possible opacity is near the check box control, 

![image](https://user-images.githubusercontent.com/10267317/90791141-85fb2780-e311-11ea-9aaf-5665a512df76.png)

Thanks.

**Comment by dayjournal** [comment]
@webmap2015 

Please elaborate on the first question.
The second question may require some CSS adjustments.

**Comment by webmap2015** [comment]
Hi,
I'm dragging (moving the slider) to the right or left simultaneously.
Opacity control is not working.

Two events are working .
mouse click
drag and drop

Thanks.

**Comment by dayjournal** [comment]
@webmap2015 

Thank you for your suggestions.
It seems to be working in my environment.
It would be very helpful if you could create a pull request.
