### ISSUE TITLE
Although collapsed is true, the control does not collapsed

### ISSUE THREAD

**Issue by lesnoj** [dayjournal/Leaflet.Control.Opacity#12]
Hallo!
Your plugin is impressive! Thank you for creation!
I found a bug in file L.Control.Opacity.js.
This bug is visible on a device with a touchscreen only.
Although collapsed is true, the control does not collapsed if I panning or scaling the map. 
This go on until I tap the screen in the map area on purpose.

To fix this, line 52 of your code:
`52			this._map.on('click', this.collapse, this);`
should be replaced with:
`52 			this._map.on('click zoom move', this.collapse, this);`

With best regards.

**Comment by dayjournal** [comment]
@lesnoj 

It seems to be working in my environment.
Do you have an image?

**Comment by lesnoj** [comment]
Yes, I have:

[https://yadi.sk/i/FT74GwSPPv28lg](url)

**Comment by lesnoj** [comment]
Yes, I have:
[https://yadi.sk/i/FT74GwSPPv28lg](url)

**Comment by dayjournal** [comment]
@lesnoj 

I couldn't reproduce the phenomenon with Chrome and Safari on my iPhone. 
Is the video on Android?

**Comment by dayjournal** [comment]
@lesnoj 

Here is the normal behavior when the collapsed option is true.
The control will only open when you click on it.

### code

```javascript
//LayerControl
L.control.layers(
    Map_BaseLayer,
    Map_AddLayer,
    {
    collapsed: true
    }
).addTo(map);

//OpacityControl
L.control.opacity(
    Map_AddLayer,
    {
    collapsed: true
    }
).addTo(map);
```

### PC

![sample210111_01](https://user-images.githubusercontent.com/7871642/104143157-b72fdd80-5401-11eb-8115-2ca73c9ba8e6.gif)


### Tablet

![sample210111_02](https://user-images.githubusercontent.com/7871642/104143357-72587680-5402-11eb-9a67-3268b1859f90.gif)

**Comment by lesnoj** [comment]
Thank you for the answer and for the video!
Now I can see that the control is collapse when plugin is installed on the iPad.
Video I sent shows how the plugin works on a Lenovo tab 4 10 device, OS Android 7.0, browser Chrome.
Undoubtedly, I have the collapse option set to true. This is confirmed by the fact that control collapsing when I tap the screen in the map area on purpose

**Comment by dayjournal** [comment]
@lesnoj 

It seems to happen only on Android.
Can I fix it by changing the code in the plugin as follows?
`this._map.on('click zoom move', this.collapse, this);`

**Comment by lesnoj** [comment]
Yes, of course, you can!

**Comment by dayjournal** [comment]
@lesnoj 

Updated to the latest version. Please check it.
