### ISSUE TITLE
Dash component

### ISSUE THREAD

**Issue by brookmay** [dayjournal/Leaflet.Control.Opacity#17]
Hi,

Great leaflet plugin! We've been trying to look for something like this to incorporate in our app and this seems like a great fit.

I'm actually trying to wrap this plugin in a dash component so that it can be used in a python based dash app. The issue isn't related to this plugin, but related more to leaflet in general. This is the error I get - 

Basically, a map would be initialized in the dash app using dash-leaflet and within the leaflet-control-opacity's dash's component, I'm trying to get the same map instance using react-leaflet's useMap() method to do the following - 

`L.control.layers(
    Map_BaseLayer,
    Map_AddLayer,
    {
    collapsed: false
    }
).addTo(**_map_**);`

But if I do that I get the below error -
"No context provided: useLeafletContext() can only be used in a descendant of <MapContainer>"

I was wondering if you've come across this issue before. Can you please help?

Thanks,

**Comment by dayjournal** [comment]
@tanvij28 

I'm sorry, I don't know, I've never installed this plugin in react-leaflet.
