### ISSUE TITLE
Request : Allow opacity change when slider dragging

### ISSUE THREAD

**Issue by Kernonen** [dayjournal/Leaflet.Control.Opacity#18]
Hi, 
Thank you very much for your very useful plugin ! 
I think this can be very much improved if you allow the map opacity to change while the slider is dragged by the user. It could add a lot of smoothness in the manipulation.

**Comment by dayjournal** [comment]
@Kernonen 
Hi,
Thanks for the suggestion. I will consider it.
If you have any suggestions for improvement, please make a pull request.

**Comment by Kernonen** [comment]
Hello,
I tried the pull request menu but it doesn’t seem to let me write one

**Comment by dayjournal** [comment]
@Kernonen 
Hi,
Can you fork the repository, modify the code, and send me a pull request?

**Comment by Kernonen** [comment]
Actually, that’s the point, i don’t know how to modify the code, i’m not a coder

**Comment by dayjournal** [comment]
@Kernonen 
Hi,
The repository has been updated to the latest version. 
I think it is resolved.

[https://dayjournal.github.io/Leaflet.Control.Opacity](https://dayjournal.github.io/Leaflet.Control.Opacity)

**Comment by Kernonen** [comment]
It is working very well ! Thank you very much for this, I really do appreciate !
