### ISSUE TITLE
Slider issues with Safari

### ISSUE THREAD

**Issue by Kernonen** [dayjournal/Leaflet.Control.Opacity#19]
On Mac Safari, sliders opacity have issues : 
- Blue style is not applied to cursor
- More important, opacity doesn't change when cursor moves a long distance on track. We have to click on track for opacity change to be effective. 
- Also, as suggested before, it would be amazing to see opacity change while dragging thumb. 

Thanks for the good work !

**Comment by dayjournal** [comment]
@Kernonen 
Hi,
I would like to have a video or picture of the situation.

**Comment by Kernonen** [comment]
Hereis a short video of the 2 issues : 
- opacity only changes when mouse release after drag (would be great to see opacity change while dragging)
- opacity doesn't change when cursor moves a long distance on track. We have to click on track for opacity change to be effective.
https://www.laurentgontier.com/Click.mp4

**Comment by dayjournal** [comment]
@Kernonen 
Hi,
The repository has been updated to the latest version. 
I think it is resolved.

[https://dayjournal.github.io/Leaflet.Control.Opacity](https://dayjournal.github.io/Leaflet.Control.Opacity)
