### ISSUE TITLE
Update opacity when slider is changed by keyboard

### ISSUE THREAD

**Issue by JarnoRFB** [dayjournal/Leaflet.Control.Opacity#20]
Hi, very nice component!

Currently it is possible to move the slider with the keyboard, but the only the slider, not the opacity does update in this case.

**Comment by dayjournal** [comment]
@JarnoRFB 
Hi,
I would like to have a video or picture of the situation.

**Comment by dayjournal** [comment]
@JarnoRFB 
Hi,
The repository has been updated to the latest version. 
I think it is resolved.

[https://dayjournal.github.io/Leaflet.Control.Opacity](https://dayjournal.github.io/Leaflet.Control.Opacity)

**Comment by JarnoRFB** [comment]
@dayjournal Gives a beautiful smooth appearance when using the keyboard. Thanks for fixing!
