### ISSUE TITLE
possibility to remove OpacityControl

### ISSUE THREAD

**Issue by YassineBouzeya** [dayjournal/Leaflet.Control.Opacity#24]
I am trying to remove and add the opacityControl depending on newly added layers... but there does not seem to be an `L.control.remove(map)` or `L.control.removeFrom(map)` option

**Comment by dayjournal** [comment]
@YassineBouzeya 
Hi,
Layers need to be set at initialization. 
It is not possible to add them later.

**Comment by YassineBouzeya** [comment]
thank you
