### ISSUE TITLE
Only show when an additional layer is selected.

### ISSUE THREAD

**Issue by jolyonralph** [dayjournal/Leaflet.Control.Opacity#4]
Is it possible to make the control only display when one or more of the additional layers are on the map?

**Comment by jolyonralph** [comment]
This sort of works, but it's a bit of a hack (requires jquery)


   var slidey = L.control.opacity(
                        opacitymaps
                    ).addTo(map).getContainer();

                    slidey.style.visibility="hidden";

                    $(".leaflet-control-layers-selector[type='checkbox'").change(function() {

                        if($(".leaflet-control-layers-selector[type='checkbox']:checked").length)
                            slidey.style.visibility="visible";
                        else
                            slidey.style.visibility="hidden";

                    });

**Comment by dayjournal** [comment]
Hi.
It is not created by layer ON / OFF.
It is useful to be an optional feature.
If possible, I want you to realize that idea with pull requests.
In that case, please create in easy-to-understand JavaScript.
