### ISSUE TITLE
mobile bug

### ISSUE THREAD

**Issue by Lepizh** [dayjournal/Leaflet.Control.Opacity#7]
Hello,

unfortunately there is a bug in mobile view - changes on opacity-sliders are not applied to the map
without tapping on the layer-tilte within Leaflet.Control.Opacity.
There is some mobile/touch-Support missing...

Maybe this could be fixed someday!?

Kind regards,
Dominik

**Comment by Lepizh** [comment]
reproducable even with your demo-page:
https://dayjournal.github.io/Leaflet.Control.Opacity

**Comment by Lepizh** [comment]
fixed it for me local by adding this line
`L.DomEvent.on(input, 'touchstart', this._onInputClick, this);`

at this line:
https://github.com/dayjournal/Leaflet.Control.Opacity/blob/e478e3390fabc93554ca4aba3aed11bee665c1d8/src/L.Control.Opacity.js#L126

**Comment by dayjournal** [comment]
Thank you for your suggestions.
It would be very helpful if you could create a pull request.
